### PR TITLE
add a new setting youtube_rel

### PR DESCRIPTION
**Pull request by frisi**
this is about stopping youtube from showing related (and sometimes inappropriate ;-) content when the video ended.

http://youtu.be/yourvideo?rel=0 did not work any longer. i asked the embedly support for help and they told me to pass `youtube_rel=0` to oembed.

this branch translates rel=0 to youtube_rel=0 for backward compatibility and also adds a new configuration option.

js was minified using http://jscompress.com/

i also did a little css/html cleanup. the empty div got "eaten" by the javascript, so i added the clear to the panel containing the buttons to have them in a separate line.

### CODE REVIEW

**Comment by dek4nice** [comment]
What about to convert transform.py:default_services variable from string to list type ?
This variable must be more flexible for customization and merging.

**Comment by chervol** [comment]
@dek4nice  making `transform.py:default_services` a list makes absolutely no sense in terms of support. As it is a directly copy/pasted regular excretion from Embedly.

**Comment by dek4nice** [comment]
Show please the code or url where from it copied.


Среда,  6 мая 2015, 5:28 -07:00 от Volodymyr Cherepanyak <notifications@github.com>:

**Comment by kroman0** [comment]
https://github.com/collective/collective.embedly/blob/master/collective/embedly/transform.py#L50

**Pull request merged**
